### ISSUE TITLE
[Bug]: Incomplete conda setup instructions

### ISSUE THREAD

**Issue by COTHSC** [42-AI/Elegant-Elegans#13]
### Description

Unable to resolve dependencies when trying to setup wf_ntp 

### What happened?

When following the setup instructions for wf_ntp, this instruction:
conda install -f conda_wf_ntp_requirements.txt

led to a package not found error

### Expected behaviour

Successful install of dependencies from dependency file.

### Environment

- Fedora linux 36
- Branch that causes this bug: main

### Steps to reproduce

Try to install dependencies with conda

<img width="714" alt="Screenshot 2022-06-06 at 17 57 11" src="https://user-images.githubusercontent.com/53475390/172198758-39b3d004-f567-46d6-a9b5-7c2e6ebccd83.png">
a

### Relevant log output

```C++
See image
```

### Proposed solution

Modify the setup.MD file

**Comment by madvid** [comment]
Seems to be outdated
