### ISSUE TITLE
feature (converter data) : convert image to video

### ISSUE THREAD

**Issue by jhparkkkk** [42-AI/Elegant-Elegans#16]
### User Story

I want to convert any .TIFF image to AVI and MP4 types video.  
so that i can use these data for WF NTP

### Acceptance Criteria

For this task several development need to be done:
* a **parser** to retrieve the **path** where tiff files are expected to be.
* a **checker** to inspect the path.
* **parser** to retrieve **information** about the collection of images tiff from the `metadata.json` within the path
* a **ckecker** based on the information retrieve from the json file
* a video constructor

task may be divided into 3 parts:
* parser and a checker about the path argument
* parser and checker about the information from json
* the video constructor

### Definition of Done

Tests : 
* first part (@jhparkkkk & @shell02 )
- [ ] `path arg` : is a string and is a path to a directory.
- [ ] check there are .tiff files  within the directory and a json file.
    - [ ] case 1: there are only .tiff files and a json file
    - [ ] case 2:.tiff files a json and other files
    - [ ] case 3: no tiff files or/and json file 
- [ ] check access to the directory
 * Second part (@rcatini & @COTHSC)
- based on the json file check if 
    - [ ] .tiff files are valid (may need to check if there is header in tiff file and check it). 
    - [ ] .tiff files are of the same size 
    - [ ] .tiff files have the same pattern (or the name is identical to those one can find in the json)  
    - [ ] there is no missing tiff
    - [ ] check minimum number of files to convert (100 files)
    - [ ] retrieve frame rate from the json file. 
* Third part (to determine)
- [ ] image to video converter

**Comment by madvid** [comment]
* for the parsing, the use of `argparse` library may be useful
* to retrieve information from json, i suggest the use of context manager the use of a function load from json module.
* to verify the arg path is a path, there might be something in os.path module
* for the test, we will use pytest (see [documentation here](https://docs.pytest.org/en/7.1.x/getting-started.html))

**Comment by madvid** [comment]
@jhparkkkk & @shell02 & @COTHSC & @rcatini
You have to comment this issue to specify what you are in charge of

**Comment by jhparkkkk** [comment]
- Either one of us write entirely all the functions (path arg, check .tiff / json, check access) and the other writes the unit tests
- Either one is in charge of the first and last bullet point and the other of the second

 however, we decided we would begin together this work tomorrow at 42
