### ISSUE TITLE
parser & checker (images to video conversion): path argument parsing and checking

### ISSUE THREAD

**Issue by madvid** [42-AI/Elegant-Elegans#17]
### User Story

I want to convert any .TIFF image to AVI and MP4 types video.  
so that i can use these data for WF NTP

To do so, I need to parse an argument being supposely the path to the directory containing:
* several tiff images
* 1 json which may be metadata concerning the video settings.

### Acceptance Criteria

Via the command
```bash
python -m converter --path [path_arg]
```
The program `converter` will check:
- [x] `path_arg` is a directory
- [x] the user has access to this directory
- [x] in the directory, there are:
    * at least **NB_LIMIT** .tiff files and a json file, plus the following cases must be handled:
        * case 1: there are only .tiff files and a json file
        * case 2:.tiff files a json and other files
        * case 3: no tiff files or/and json file 

### Definition of Done

- [x] unit tests have been written and submitted. Tose tests includes:
    - [x] path does not exist
    - [x] user does not have access to the directory
    - [x] `path_arg` is not a directory
    - [x] directory does not contained tiff nor json file
- [ ] Product Owner accepts the User Story
- [ ] Acceptance criteria met

Defined by CICD:
- Code reviewed
- black compliant
- Unit tests passed
- Functional tests passed
- Non-Functional requirements met

**Comment by madvid** [comment]
Right, @jhparkkkk and @shell02.
You should add an argument to the parser object, to be able to define the output path and filename

**Comment by madvid** [comment]
I let you decide between you (@jhparkkkk , @shell02 , @cnstll , @p-lg-ux )

**Comment by madvid** [comment]
@jhparkkkk & @shell02 how is it going ?

**Comment by p-lg-ux** [comment]
Shouldn't the parser allow both "tiff" **and "tif"** extensions in the directory (instead of just "tiff") ?
