### ISSUE TITLE
parser & checker (images to video conversion): parsing the json to retrieve information about tiff images

### ISSUE THREAD

**Issue by madvid** [42-AI/Elegant-Elegans#18]
### User Story

I want to convert any .TIFF image to AVI and MP4 types video.
so that i can use these data for WF NTP

To do so, I need to parse an argument being supposely the path to the directory containing:
* several tiff images
* 1 json which may be metadata concerning the video settings.

This part is dealed in the issue #17 and is the first step realised by the execution of:
```bash
python -m converter --path [path_arg]
```

Based on `path_arg` I want that the program `converter.py` to parse the json file and retrieve the different information to check the validity of the tiff files.

The handle of the variable frame rate is tricky (related issue: #24 ). Thus to level of development is expected:
- average the frame rate a construct a video with this average.
- use the instant frame rate

It may be important for futur analysis to keep a track of the instant frame rate. Two choices are possible:
- generate a json with the time interval between consecutive frame
- develop the functions to easily retrieve this information from the json file containing the metadata video.
This choice is at the developper discretion.
 
### Acceptance Criteria

- based on the json file check if 
    - [x] .tiff files are valid (may need to check if there is header in tiff file and check it). 
    - [x] .tiff files are of the same size 
    - [x] .tiff files have the same pattern (or the name is identical to those one can find in the json)  
    - [x] there is no missing tiff
    - [ ] check minimum number of files to convert (100 files)
    - [ ] retrieve frame rate from the json file. 

### Definition of Done

- [ ] Product Owner accepts the User Story
- [ ] Acceptance criteria met

Defined by CICD:
- Code reviewed
- black compliant
- Unit tests passed
- Functional tests passed
- Non-Functional requirements met

**Comment by madvid** [comment]
@COTHSC user story is updated

**Comment by madvid** [comment]
@COTHSC and @rcatini, for the tests you can perform some of them to start with the URI:
- `s3://lab-nematode/tests/test_1/ `  is valid
- `s3://lab-nematode/tests/test_2/` is invalid because name of a tiff is modified
- `s3://lab-nematode/tests/test_3/` is invalid because a file tiff has been deleted
- `s3://lab-nematode/tests/test_4/` invalid because the size of an image has been modify in the metadata.json

**Comment by p-lg-ux** [comment]
Instead of a list of the time intervals between the frames, it could be better to have a dictionary with the format
`dict =	{
  "filename0.tiff": interval0_ms,
  "filename1.tiff": interval1_ms,
  ...,
   "filenameN.tiff": intervalN_ms,
}`
where interval0_ms is equal to 0.
