### ISSUE TITLE
add of extension (formating & environment): install extension pylance and autodocstring

### ISSUE THREAD

**Issue by madvid** [42-AI/Elegant-Elegans#25]
### User Story

As a contributor,
You need to add the extension Pylance and autodocstring in your VS Code, while I will configure the pre-commit to check automatically the format of the code commited.

### Acceptance Criteria
No need to create a branch !!

every contributor installed these extensions:

![image](https://user-images.githubusercontent.com/37487348/172727441-a4a9b7ac-a93b-41af-a7c4-1653b087feb7.png)

![image](https://user-images.githubusercontent.com/37487348/172727506-27d18262-09fd-4241-ad8e-a6082d18f6ec.png)

### Definition of Done

- [x] @rcatini has installed the extension 
- [x] @cnstll  has installed the extension
- [x] @COTHSC  has installed the extension
- [x] @jhparkkkk  has installed the extension
- [x] @shell02  has installed the extension
- [x] @p has installed the extension

**Comment by jhparkkkk** [comment]
extensions installed
