### ISSUE TITLE
Set-up(env CeleST): Find a way to work with CeleST

### ISSUE THREAD

**Issue by p-lg-ux** [42-AI/Elegant-Elegans#33]
### User Story

As a CeleST user,
I want to launch and execute the CeleST software in a dedicated environment,
so that we can import a video, execute a task and retrieve the output.
Concerning the environment, different leads are possible: 
* using latest version of Octave and debugging (run and crash)
* within a VM (Linux/Windows), use a former version of Matlab (2015b to 2017b)
* within a VM (Linux/Windows), use the latest version of Matlab
* within a VM, use a former version of Octave (2015 to 2017)

CeleST code source can be found here: http://celest.mbb.rutgers.edu/

### Acceptance Criteria

- [x] Create a new Matlab version (integrate the code in the repository github of Elegant-Elegans) in a directory `CeleST`.
- [x] CeleST is working properly on GNU Octave (version in Settings section).
  - [x] A directory CeleST with all the code working in Octave (`CeleST/`).
  - [x] A documentation explaining how to execute the code  (in `CeleST/how_to.md`).
- [x] Documentation explaining how to import TIFF images and the processing of these data.
- [x] Functionalities concerning the analysis (available on the processing window frame) must work.
- [ ] Documentation to install Octave via  flatpak (in `Setup.md`). 

### Definition of Done

- [ ] Product Owner accepts the User Story
- [ ] Acceptance criteria met

Defined by CICD:
- Set up instructions have been written

### Settitngs:
- Ubuntu 20.4 or 22.04
- GNU Octave, version 7.1.0

**Comment by madvid** [comment]
@p-lg-ux starts with the first lead (lastest version of Octave and debugging approach)

**Comment by madvid** [comment]
For the moment we have edited 2 files : CeleST.m and CSTProcessVideos.m
make sure to import image package in Octave by typing in the octave interface `pkg install -forge image`
You will probably have an error about a directory `/run/user/snap.octave`, you will have to create it and edit the acress via chmod

[edited_sources.zip](https://github.com/42-AI/Elegant-Elegans/files/8936030/edited_sources.zip)

**Comment by p-lg-ux** [comment]
@madvid For information purpose, could you precise the ubuntu and octave versions used ?

**Comment by madvid** [comment]
@p-lg-ux update of the issue done
