### ISSUE TITLE
feature (wfntp): Implementation of the Activity Index 

### ISSUE THREAD

**Issue by cnstll** [42-AI/Elegant-Elegans#45]
### User Story

As a WF NTP user,
I want to launch and run wf ntp,
so that I can output the activity index for each worm.

### Acceptance Criteria

- [x] The activity index calculation is implemented in the `WF_NTP_script.py`
- [x] The activity index values are outputted in 'particles.csv'  for each "particle"
- [x] The activity index measures (mean, std, error on mean and median) are outputted in 'results.txt'

### Definition of Done

- [ ] Product Owner accepts the User Story
- [ ] Acceptance criteria met
- [ ] New data has been `dvc push`

Defined by CICD:
- Code reviewed
- black compliant
- Unit tests passed
- Functional tests passed
- Non-Functional requirements met

**Comment by cnstll** [comment]
Report overview was moved to #60 for a more atomic issue

**Comment by madvid** [comment]
Done in branch #45 (correspond to the PR #65)
