### ISSUE TITLE
Set-Up (wfntp): Merge wfntp submodule into main repo

### ISSUE THREAD

**Issue by cnstll** [42-AI/Elegant-Elegans#46]
### User Story

As a dev,
I want to merge wfntp submodule into main ,
so that I can edit wfntp code within the current repo.

### Acceptance Criteria

- [ ] All the code from wf_ntp submodule is merge into main
- [ ] keep git history of submodule (do we care?)

### Definition of Done

- [ ] Product Owner accepts the User Story
- [ ] Acceptance criteria met
- [ ] New data has been `dvc push`

Defined by CICD:
- Code reviewed
- black compliant
- Unit tests passed
- Functional tests passed
- Non-Functional requirements met

**Comment by cnstll** [comment]
@COTHSC this [article](https://medium.com/walkme-engineering/how-to-merge-a-git-submodule-into-its-main-repository-d83a215a319c) might be useful

**Comment by madvid** [comment]
At the end, code was already in the PR of @COTHSC, I accept it despite It should not be acceptable.

**Comment by madvid** [comment]
I let you close this issue and delete the branch @cnstll
