### ISSUE TITLE
docs(setup): typo and error on linux

### ISSUE THREAD

**Issue by ezalos** [42-AI/Elegant-Elegans#55]
### User Story

As a user,
I want to setup wfntp on linux,
so that other cna use it.

### Acceptance Criteria

- [ ] able to launch under linux

### Definition of Done

- [ ] Product Owner accepts the User Story
- [ ] Acceptance criteria met
- [ ] New data has been `dvc push`

Defined by CICD:
- Code reviewed
- black compliant
- Unit tests passed
- Functional tests passed
- Non-Functional requirements met

**Comment by ezalos** [comment]
@madvid 

Step 4 is broken 
```
Ouvrir le fichier WF_NTP/WF_NTP/WF_NTP_script.py et remplacer coordinates='xy' par coordinates='rc' à la ligne 287.
```

**Comment by madvid** [comment]
I made a mistake, I did the correction and push thinking I was on the branch but I was on main.. But it is corrected anyway
